#!/usr/bin/env node
/**
 * Generate TypeScript types and a standalone AJV validator from the canonical
 * JSON Schema (schema/por-que.schema.json). Output lands in src/generated/
 * (gitignored). Deterministic: same schema in, same files out.
 */
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { compile } from 'json-schema-to-typescript';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = path.join(root, 'schema', 'por-que.schema.json');
const outDir = path.join(root, 'src', 'generated');

const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
fs.mkdirSync(outDir, { recursive: true });

// 1. Types
const types = await compile(schema, 'ParquetFile', {
    additionalProperties: false,
    bannerComment:
        '/* eslint-disable */\n/**\n * GENERATED by scripts/generate.mjs from schema/por-que.schema.json.\n * Do not edit by hand.\n */',
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
});
fs.writeFileSync(path.join(outDir, 'por-que.d.ts'), types);

// 2. Standalone validator (ESM)
const ajv = new Ajv2020({ allErrors: true, strict: false, code: { source: true, esm: true } });
// `base64url` is a documentation-only format on the byte-value fields; accept
// it as a no-op so ajv doesn't warn about an unknown format.
ajv.addFormat('base64url', true);
const validate = ajv.compile(schema);
let validatorCode = standaloneCode(ajv, validate);
// standalone emits `export const default = ...` under esm which is a syntax
// error; normalize to a real default export.
validatorCode = validatorCode.replace(/export const default =/, 'const validate =');
if (!/export default/.test(validatorCode)) {
    validatorCode += '\nexport default validate;\n';
}
fs.writeFileSync(path.join(outDir, 'validate.js'), validatorCode);

fs.writeFileSync(
    path.join(outDir, 'validate.d.ts'),
    `/* GENERATED. Do not edit. */
import type { ParquetFile } from './por-que';

export interface ValidationError {
    instancePath: string;
    schemaPath: string;
    keyword: string;
    message?: string;
    params: Record<string, unknown>;
}

interface ValidateFn {
    (data: unknown): data is ParquetFile;
    errors?: ValidationError[] | null;
}

declare const validate: ValidateFn;
export default validate;
`
);

// prettier-format the generated files so format:check stays green.
try {
    execSync(`npx prettier --write "${outDir.replace(/\\/g, '/')}/*.{ts,js}"`, {
        cwd: root,
        stdio: 'ignore',
    });
} catch {
    // formatting is best-effort; generated dir is gitignored anyway.
}

console.log('Generated src/generated/{por-que.d.ts,validate.js,validate.d.ts}');
