#!/usr/bin/env node
/**
 * Generate TypeScript types and standalone AJV validators from the canonical
 * JSON Schema (static/vendor/por-que.schema.json, extracted from the pinned
 * por-que wheel by `npm run wheel`). The schema is a union of two dump roots
 * (`file` and `metadata`); we compile one validator per root so the load
 * boundary can dispatch on `_meta.model`. Output lands in src/generated/
 * (gitignored). Deterministic: same schema in, same files out.
 */
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { compile } from 'json-schema-to-typescript';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// por-que's dump-schema.json, extracted from the pinned wheel by
// scripts/fetch-wheels.py, so codegen and runtime share one schema.
const schemaPath = path.join(root, 'static', 'vendor', 'por-que.schema.json');
const outDir = path.join(root, 'src', 'generated');

if (!fs.existsSync(schemaPath)) {
    console.error(
        `Missing ${path.relative(root, schemaPath)} (extracted from the pinned por-que wheel).\nrun: npm run wheel`
    );
    process.exit(1);
}
const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
fs.mkdirSync(outDir, { recursive: true });

// 1. Types. Compiling the union schema emits the root union plus an interface
// for every $def (both roots included) thanks to declareExternallyReferenced +
// unreachableDefinitions.
const types = await compile(schema, 'PorQueDump', {
    additionalProperties: false,
    bannerComment:
        '/* eslint-disable */\n/**\n * GENERATED by scripts/generate.mjs from the pinned por-que wheel schema.\n * Do not edit by hand.\n */',
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
});
fs.writeFileSync(path.join(outDir, 'por-que.d.ts'), types);

// 2. Standalone validators (ESM), one per root, as named exports.
const ajv = new Ajv2020({ allErrors: true, strict: false, code: { source: true, esm: true } });
// `base64url` is a documentation-only format on the byte-value fields; accept
// it as a no-op so ajv doesn't warn about an unknown format.
ajv.addFormat('base64url', true);
ajv.addSchema(schema, 'dump');
const validatorCode = standaloneCode(ajv, {
    validateFile: 'dump#/$defs/ParquetFile',
    validateMetadata: 'dump#/$defs/MetadataExport',
});
fs.writeFileSync(path.join(outDir, 'validate.js'), validatorCode);

fs.writeFileSync(
    path.join(outDir, 'validate.d.ts'),
    `/* GENERATED. Do not edit. */
import type { ParquetFile, MetadataExport } from './por-que';

export interface ValidationError {
    instancePath: string;
    schemaPath: string;
    keyword: string;
    message?: string;
    params: Record<string, unknown>;
}

interface ValidateFileFn {
    (data: unknown): data is ParquetFile;
    errors?: ValidationError[] | null;
}

interface ValidateMetadataFn {
    (data: unknown): data is MetadataExport;
    errors?: ValidationError[] | null;
}

export declare const validateFile: ValidateFileFn;
export declare const validateMetadata: ValidateMetadataFn;
`
);

// prettier-format the generated files so format:check stays green.
try {
    execSync(`npx prettier --write "${outDir.replace(/\\/g, '/')}/*.{ts,js}"`, {
        cwd: root,
        stdio: 'ignore',
    });
} catch {
    // formatting is best-effort; generated dir is gitignored anyway.
}

console.log('Generated src/generated/{por-que.d.ts,validate.js,validate.d.ts}');
